### ISSUE TITLE
rookie question!

### ISSUE THREAD

**Issue by spants** [jeantil/autokbisw#10]
How do I use this?

I can't see any binaries in the repository... I'd like to use this as I have an internal British keyboard and external British PC keyboard.

Unfortunately I am not familiar with xcode or swift.
Many thanks

**Comment by jeantil** [comment]
either you build from source or you can download the latest (and for now only) release from the release section of the repository: 
https://github.com/jeantil/autokbisw/releases

Then follow the setup instructions of the readme : 
https://github.com/jeantil/autokbisw#installation

best regards :)
