### ISSUE TITLE
Doesn't seem to be working with Mojave

### ISSUE THREAD

**Issue by leecolarelli** [jeantil/autokbisw#22]
Hi, thanks for this... it is exactly what i was looking for!

However, it doesn't seem to be working in my setup. I am using Mac OS Mojave v10.14.1 and have the software installed via homebrew. It was added to the homebrew startup list and is verified as running.

Forgive me if I'm being dumb but that's all that should need doing right? It's just not switching when a different keyboard is used.

Happy to help in any way i can.

**Comment by andremetzen** [comment]
Same here. I just installed on Mojave 10.14.1, I see it running but it's not switching the input source and I plug my keyboard.

**Comment by jeantil** [comment]
Hi, 

Thanks for reporting the issue. I haven't updated yet for fear of breaking tools, I didn't expect this one to break.

Just to make sure as the documentation is still a bit sketchy : autokbisw does't detect the input source automatically. 
It only remembers the last input source used on a given keyboard and restores that input source when the keyboard is used again. This means you need to manually change the input source once when you plug a new keyboard.  

I'll update to mojave as soon as possible. In the mean time, if one of you could restart the program with debug on and attach the log files here I would be very grateful. Have a look at ~/Library/LaunchAgents/homebrew.mxcl.autokbisw.plist to enable output logging.

**Comment by benssson** [comment]
I thought it wasn't working for me either but once I set the input source for my keyboards again its switching correctly.

**Comment by W3D3** [comment]
Working flawlessly on Mojave for me. Thanks for the awesome tool.

**Comment by jeantil** [comment]
@leecolarelli @andremetzen I finally switched to mojave a few weeks ago but I don't encounter any issue on mojave. Do you still have the problem ? if you do, could you run the debug mode and provide the log file along with the precise steps you took. 

i'll close the issue for the meantime, do not hesitate to comment on it with the additional information and I'll reopen it.

**Comment by leecolarelli** [comment]
Hi. Sorry for the slow reply. I still have issues... I have enabled debug mode as requested and will provide an update soon.

**Comment by jeantil** [comment]
@leecolarelli  no problem, I'm curious to see the detailed traces. I am on mojave myself now and it works fine for me

**Comment by leecolarelli** [comment]
I have checked the log but it is empty. I have included the plist file below so you can see that it's correct.

One other thing is that i noticed that autokbisw was not running this morning when i checked the file. It is installed via homebrew, so I could see it wasn't started when running brew services list. All my other brew programs are running fine so i'm not sure why this wasn't running?

Here's the plist file:-
`<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.autokbisw</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/Cellar/autokbisw/1.2.0/bin/autokbisw</string>
    </array>
       
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/usr/local/var/log/autokbisw.log</string>
    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/autokbisw.log</string>
    
  </dict>
</plist>`

**Comment by jeantil** [comment]
it's a bit hard to tell with all the formatting removed but I think the 'verbose' mode is still disabled in your configuration. 
```
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.autokbisw</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/Cellar/autokbisw/1.2.0/bin/autokbisw</string>
      <string>-v</string>
    </array>    
    <!-- <string>--location</string>  -->
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/usr/local/var/log/autokbisw.log</string>
    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/autokbisw.log</string>       
  </dict>
</plist>
```

>All my other brew programs are running fine so i'm not sure why this wasn't running?

Sorry I can't help with that remotely. As far as I can tell the brew installer works since that's how I installed it myself :) it is possible that there  is a syntax error in the plist file which prevents launchd from starting autokbisw.
