### ISSUE TITLE
Feature: Also store switching of modifier keys for each keyboard

### ISSUE THREAD

**Issue by NorfeldtAbtion** [jeantil/autokbisw#24]
I absolutely ❤️this fix! It make pairing so much easier - thank you so much! 😊 

We have some windows users that have converted to mac switch the modifier keys (ctrl and cmd) to make the transition easier. 

https://i0.wp.com/www.techjunkie.com/wp-content/uploads/2016/04/mac-osx-keyboard-modifier-keys.png?ssl=1

Would it be possible to store the setting for each keyboard as well?

**Comment by jeantil** [comment]
I'm sorry I couldn't get to this earlier, spare time is really scarce at the moment.  

A quick search shows that it should indeed be possible to programmatically remap the modifiers key when swithching keyboards. There is even a code sample to do that and the mapping table in this note  https://developer.apple.com/library/archive/technotes/tn2450/_index.html

I probably will never write the code myself, my mbp is dying and I'll be moving over to linux. I'll review a PR though and I'm willing to pass the keys off to anyone willing to maintain and extend autokbisw.

**Comment by jeantil** [comment]
hello, you may want to have a look @ohueter's fork https://github.com/ohueter/autokbisw he has fixed the build for newer versions of OSX and may be interested in adding this feature or reviewing a PR for it
