### ISSUE TITLE
Unfortunately, not working with my setup

### ISSUE THREAD

**Issue by z0ph** [jeantil/autokbisw#27]
Hi Jean,

Unfortunately, or maybe I missing something, the switch does not operate on my setup

- MBP
- macOS Catalina
- Installed with Brew (with Xcode)
- Using either MBP (Azerty) or USB Vortex Mechanical Keyboard (QWERTY)

I've tried a few times using sublime text to switch from MBP keyboard or USB one... without success..

I just want an automagic switch between input source/keymap.

Do we have any troubleshooting procedures or verification steps to do a diagnostic?

```
> ps ax|grep autok
98748   ??  S      0:00.04 /usr/local/Cellar/autokbisw/1.2.0/bin/autokbisw
99076 s004  SN     0:00.02 sudo autokbisw
99095 s004  SN     0:00.03 autokbisw
```

Thanks,
Victor

**Comment by z0ph** [comment]
I think I will stick to this simple method: 

![image](https://user-images.githubusercontent.com/20846187/75902710-bffa6f00-5e40-11ea-92bc-584ece761ff1.png)

**Comment by jeantil** [comment]
I'm on vacation with the kids and a spotty internet connection

Check https://github.com/jeantil/autokbisw/issues/22

There are more explanations on how autokbisw works and some directions on
how to enable debug mode.

I'll have a look next week when I get back if you haven't solved your issue
by then

Le mer. 4 mars 2020 à 17:51, Victor GRENU <notifications@github.com> a
écrit :
