### ISSUE TITLE
Stops working after sleep

### ISSUE THREAD

**Issue by gochito** [jeantil/autokbisw#28]
I have a 2020 13 inch MB pro running Mojave with EN KB and an external Spanish Apple BT keyboard. It launches at startup no problem, but after the machine goes to sleep, autokbisw stops working... the executable is running, but won't change the input source anymore. I end up having to run it manually and the ps output is:

 501   641     1   0  9:06AM ??         0:05.35 /usr/local/bin/autokbisw
    0  3486  3466   0 12:27PM ttys000    0:00.09 sudo ./autokbisw
    0  3487  3486   0 12:27PM ttys000    0:02.97 ./autokbisw

Some console log entries:

default	14:49:37.339998 -0500	autokbisw	IOHIDDeviceClass::buildElements: type=1 *buffer=7fa076d5abc0 *count=4 size=384
default	14:49:37.340305 -0500	autokbisw	IOHIDDeviceClass::buildElements: type=0 *buffer=7f8040e5aaa0 *count=9 size=864
default	14:49:37.340834 -0500	autokbisw	IOHIDDeviceClass::buildElements: type=1 *buffer=7f8040c6baf0 *count=4 size=384
error	14:49:58.462046 -0500	kernel	autokbisw is not entitled for IOHIDLibUserClient keyboard access
error	14:49:58.462050 -0500	kernel	autokbisw is not entitled for IOHIDLibUserClient keyboard access

**Comment by jeantil** [comment]
this
```
error 14:49:58.462046 -0500 kernel autokbisw is not entitled for IOHIDLibUserClient keyboard access
```
looks pretty bad. something has probably changed in OSX that removes the keyboard access upon sleep. 
Since I don't own a mac anymore I can't really maintains autokbisw anymore :(

**Comment by gochito** [comment]
Jean:

Such a pity. It is a really useful utility for mixed keyboard users.

Thanks for your efforts in creating and maintaining it while you could.

Regards,

Francisco Romero

**Comment by jeantil** [comment]
Sorry i can't help anymore, the code is really not very big or complex hopefully another dev who still uses osx will pick it up :D

**Comment by jeantil** [comment]
hello, you may want to have a look @ohueter's fork https://github.com/ohueter/autokbisw he has fixed the build for newer versions of OSX maybe it also fixes your issue
