### ISSUE TITLE
Installation from binaries issue

### ISSUE THREAD

**Issue by tplobo** [jeantil/autokbisw#30]
Part of the command "launchctl" is apparently deemed [legacy](https://www.reddit.com/r/MacOS/comments/kbko61/launchctl_broken/).

It leads to the following message in Terminal:
`Load failed: 5: Input/output`

Using first `launchctl unload path/to/plist` and then `launchctl load path/to/plist` does not return the error, but also does not seem to make the binary work.

**Comment by jeantil** [comment]
hi @tplobo 

as I explain in [the readme](https://github.com/jeantil/autokbisw#this-project-is-looking-for-a-maintainer) I no longer maintain autokbisw since I don't have a mac anymore ...
 I'll be happy to transfer this repo to anyone who wants to take over the project just let me know :)

**Comment by tplobo** [comment]
Hi @jeantil!

Yeah, I saw it, but unfortunately I know very little of this kind of programming. I would have no idea not even how to start.
I tried following the instructions on the link I added in the original post, but failed miserably, hehehe... Homebrew and Source approaches also failed.

Nevertheless, I wanted to add the information here to document the issue. If we're lucky, someone may come along that knows how to tackle this.

Sorry, but thanks for the effort you've put in so far anyway.

**Comment by jeantil** [comment]
hello, you may want to have a look @ohueter's fork https://github.com/ohueter/autokbisw he has fixed the build for newer versions of OSX

**Comment by tplobo** [comment]
I'll take a look when I have a bit of time! Thanks a lot Jean!

___________________________________________________________
Tiago Pomella Lobo
Physics Engineer - Federal University of Sao Carlos (2009)
Nuclear Fusion S&T MSc. - TU/e (2016)
***@***.***
***@***.***
___________________________________________________________
________________________________
