### ISSUE TITLE
Save settings on restart

### ISSUE THREAD

**Issue by Trefex** [jeantil/autokbisw#5]
Do you think you could add an option to save the settings between restart?

**Comment by Trefex** [comment]
@jeantil I found a way to do this, but the code is under MIT license. 

Would you accept a PR that would include the MIT license for the parts explicitly marked in the code?

Thanks,

**Comment by jeantil** [comment]
I'm on vacation right now. I'll be back next week and have a look at all this. 

Thanks for proposing a PR :)
